import swaggerAutogen from 'swagger-autogen';
import app from './src/app.js';

const doc = {
  info: {
    version: "1.0.0",
    title: "Backend participantes",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:4002",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "Participantes",
      "description": "Endpoints"
    }
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",       // can be "header", "query" or "cookie"
      name: "X-API-KEY",  // name of the header, query parameter or cookie
      description: "any description..."
    }
  },
  definitions: {
    Participante: {
      id_participante: "",
      tipo_identificacion: "",
      numero_documento: "",
      primer_nombre: "",
      segundo_nombre: "",
      primer_apellido: "",
      segundo_apellido: "",
      fecha_nacimiento: "",
      sexo: "",
      pais_nacimiento: "",
      pais_residencia: "",
      departamento: "",
      municipio: "",
      comuna: "",
      barrio: "",
      estrato: "",
      telefono_fijo: "",
      telefono_celular: "",
      correo_electronico: "",
      tipo_participante: "",
      datos_empresa: [],
      usuario_id: "",
      fecha_creacion: "",
      fecha_modificacion: "",
      usuario_creacion: "",
      usuario_modificacion: ""
    }
  }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.js']

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
   await import('./src/app.js');
});